### ISSUE TITLE
InvalidOperationException for Visual Studio 2017

### ISSUE THREAD

**Issue by Delpire** [devlooped/xunit.vsix#6]
I have Visual Studio 2017 community edition installed on my machine and I am not able to get the VsixFact to work. I have the Visual Studio SDK installed through the Visual Studio installer. My version of Visual Studio is 15.7.4

I have the following test:
`
[VsixFact]  
public void Testing2()  
{  
    Assert.True(true);  
}`

When I run it, I get the following error:

> Message: System.InvalidOperationException : Cannot execute test for specified VisualStudioVersions=15.0 because there is no VSSDK installed for that version.

I even tried adding the NuGet package for Microsoft.VisualStudio.Shell.15.0 (which pulls a ton of stuff down).

**Comment by Delpire** [comment]
@kzu I tried installing VS2015 with update 1 on top of the VS2017. I still wasn't able to get my test to run. There could be some configuration I am missing.

**Comment by kzu** [comment]
Yep, the support for 2017 wasn't solid to begin with (I wrote most of the stuff when there wasn't even a 2017 at all, back in 2015).

**Comment by Delpire** [comment]
Ahh I see. I wasn't able to get it to work with 2015 either. I was having some issues with some of the linq statements not returning anything.

I believe VsVersion.cs  was one of the problems, in the constructor.

I've tried going through and fixing everything on my machine, but it seems like xUnit isn't wanting to use the test frameworks, executors, and runners you have written.

**Comment by Delpire** [comment]
So I've gotten all the way up to Visual Studio launching when the test is run, but it looks like the test itself doesn't actually run.

**Comment by kzu** [comment]
Ok, documentation still pending, but things are working great for 2017 and later :). 

It's been a long while, but perhaps you'd consider giving it another try.

Closing for now, feel free to reopen if you have issues.
